// Samples a hex-staggered 1° grid over land (Natural Earth 1:50m via world-atlas) and tags each dot
// with its country, so the page can draw a dotted map and pick on-land start/end points for migrants.
//
//   node scripts/build_world.mjs   -> data/world.js  (window.WORLD = {step, names, dots: [lon, lat, country, ...]})
import fs from 'node:fs';
import path from 'node:path';
import {feature} from 'topojson-client';

const root = path.resolve(import.meta.dirname, '..');
const topo = JSON.parse(fs.readFileSync(path.join(root, 'node_modules/world-atlas/countries-50m.json'), 'utf8'));
const countries = feature(topo, topo.objects.countries).features.filter((f) => f.properties.name !== 'Antarctica');

const STEP = 1;
const LAT_MIN = -56;
const LAT_MAX = 83;

function polygons(geom) {
  return geom.type === 'Polygon' ? [geom.coordinates] : geom.coordinates;
}

function inRing(lon, lat, ring) {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i];
    const [xj, yj] = ring[j];
    if (yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}

const shapes = countries.map((f) => {
  const polys = polygons(f.geometry);
  let [x0, y0, x1, y1] = [180, 90, -180, -90];
  for (const poly of polys) for (const [x, y] of poly[0]) {
    x0 = Math.min(x0, x); y0 = Math.min(y0, y); x1 = Math.max(x1, x); y1 = Math.max(y1, y);
  }
  return {name: f.properties.name, polys, bbox: [x0, y0, x1, y1]};
});

const names = shapes.map((s) => s.name);
const dots = [];
let row = 0;
for (let lat = LAT_MAX; lat >= LAT_MIN; lat -= STEP, row++) {
  const offset = row % 2 ? STEP / 2 : 0;
  for (let lon = -180 + offset; lon < 180; lon += STEP) {
    for (let c = 0; c < shapes.length; c++) {
      const {bbox, polys} = shapes[c];
      if (lon < bbox[0] || lon > bbox[2] || lat < bbox[1] || lat > bbox[3]) continue;
      const hit = polys.some((poly) => inRing(lon, lat, poly[0]) && !poly.slice(1).some((hole) => inRing(lon, lat, hole)));
      if (hit) {
        dots.push(+lon.toFixed(1), +lat.toFixed(1), c);
        break;
      }
    }
  }
}

fs.mkdirSync(path.join(root, 'data'), {recursive: true});
fs.writeFileSync(
  path.join(root, 'data/world.js'),
  `// generated by scripts/build_world.mjs from Natural Earth 1:50m (public domain) via world-atlas\n` +
    `window.WORLD = ${JSON.stringify({step: STEP, names, dots})};\n`,
);
console.log(`${dots.length / 3} land dots, ${names.length} countries -> data/world.js`);
